### ISSUE TITLE
ti_am335x_tsc.c -> bug step config settings for 5-wire touchscreen

### ISSUE THREAD

**Issue by elgo-ubuntu** [RobertCNelson/ti-linux-kernel#1]
There is an bug in step config for 5-wire:
Line 162:
    case 5:
        config |= ts_dev->bit_xp | STEPCONFIG_INP_AN4 |
                ts_dev->bit_xn | ts_dev->bit_yp;
        break;

It should be:
    case 5:
        config |= ts_dev->bit_xp | STEPCONFIG_INP_AN4 |
                STEPCONFIG_XNP | STEPCONFIG_YPN;
        break;

Found here: http://permalink.gmane.org/gmane.linux.kernel.input/37966

**Comment by RobertCNelson** [comment]
Which branch? If the fixed pushed to mainline, we just go to ping greg to backport to 3.14/4.1..

**Comment by elgo-ubuntu** [comment]
In branch "ti-linux-4.1.y" but also in "master"

**Comment by RobertCNelson** [comment]
I've pinged the current maintainers of that file to see what's up..

ti-linux-4.1.y is controlled by ti.com admins so i can't push to that..

Regards,
