### ISSUE TITLE
UART sending only two characters

### ISSUE THREAD

**Issue by georgekav2** [RobertCNelson/ti-linux-kernel#2]
UART driver in the latest ti-kernel version seems to send only two first characters per request. I am not sure if this bug is due to overflowing of out-buffer.

I can replicate this with kernel 4.1.13-ti-r34, using the command echo 'abcd' > /dev/ttyO2 and having a logic analyzer connected to TX. The logic analyzer can only "sense" the 'ab' characters. Speed does not make a difference. Tried both with 9600 and 115200. 

FYI, kernel 4.1.10-ti-r24 works just fine, maybe some of the next kernel would do as well.

**Comment by RobertCNelson** [comment]
@georgekav2 please upgrade to 4.1.13-ti-r35, we reverted the 8250_dma change we did in 4.1.13-ti-r34

**Comment by georgekav2** [comment]
thanks @RobertCNelson I confirm the issue is resolved in 4.1.13. Thank you for your quick answer. 

PS. Should we submit an issue post here or maybe it is better for you to do it somewhere in the ti hosted git?

**Comment by georgekav2** [comment]
thanks @RobertCNelson I confirm the issue is resolved in 4.1.13-ti-r35. Thank you for your quick answer.

PS. Should we submit an issue post here or maybe it is better for you to do it somewhere in the ti hosted git?
