### ISSUE TITLE
console=ttyO0 is always enabled by kernel command line

### ISSUE THREAD

**Issue by orgua** [RobertCNelson/ti-linux-kernel#3]
I tried to disable the console on the current versions of the two branches v4.14 and v4.19 on a BBB and had no luck:

- image is from 2020-03-12
- `/etc/default/grub` is adapted to omit console and grub updated
- `/boot/uEnv.txt` contains no overlay with a serial
- `sudo grep -rinI  'ttyO0' /etc /boot` only shows `/boot/SOC.sh` and `/etc/securetty`, both are not the culprid
- getty-services are disabled in systemctl
- even the old fragments `/bbb-uEnv.txt` and `/nfs-uEnv.txt` are not guilty
- i looked in the device tree sources and overlay sources and found no device that added something to the kernel command line

`dmesg | grep tty` still shouts `Kernel command line: console=ttyO0,115200n8`

Does anyone have a tip? I would be grateful!

**Comment by RobertCNelson** [comment]
it's set by u-boot:

https://github.com/RobertCNelson/Bootloader-Builder/blob/master/patches/v2019.04/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch#L735-L742

Regards,

**Comment by orgua** [comment]
Thanks for the fast reply Robert, 

i understand that this is the wrong medium for that, but may i ask a continuing question? do you see any chance to easily disable the console? I tried to use `fw_printenv` but can't get the `/etc/fw_env.config` straight. several threads found by google suggest to set it to `/dev/mmcblk1boot1 0x20000 0x20000`, but checking with `hexdump` or `hexedit` it tells me that it is empty. but there is some config-text on `mmcblk1`, non-zero-data begins at 0x20000, but readable text begins at 0x3#### and ends before 0x40000. i tried several combinations, no luck. Printenv still gives me a `Warning: Bad CRC, using default environment`.

**Comment by RobertCNelson** [comment]
it's set as a file:

```
CONFIG_ENV_IS_IN_EXT4=y
CONFIG_ENV_EXT4_INTERFACE="mmc"
CONFIG_ENV_EXT4_DEVICE_AND_PART="0:1"
CONFIG_ENV_EXT4_FILE="/boot/uboot.env"
```

https://github.com/RobertCNelson/Bootloader-Builder/blob/master/patches/v2019.04/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch#L534-L537

**Comment by orgua** [comment]
it is missing on my, i doublechecked with the fresh downloaded image from 

https://elinux.org/BeagleBoardUbuntu#eMMC:_All_BeagleBone_Variants_with_eMMC

- there is only an emtpy `/boot/uboot/` folder and the not-helpful `uEnv.txt`
- i must be overlooking something, because even the future-patches for your Bootloader-Builder contain this file-reference

**Comment by RobertCNelson** [comment]
Type saveenv in u-boot and the file should be generated.

**Comment by orgua** [comment]
I see :( 
This is hard to do on a remote management with a network of 20++ BBG. But anyway, thanks for your Input and years of contribution to the developer-scene! cheers
